# Generated by Django 6.0.2 on 2026-09-27 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('avatar', models.CharField(default='/assets/boy-avatar.jpg', max_length=255)),
                ('grade', models.CharField(default='Kindergarten', max_length=50)),
                ('total_score', models.IntegerField(default=0)),
                ('total_stars', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100)),
                ('game_title', models.CharField(blank=True, default='', max_length=150)),
                ('score', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('times_played', models.IntegerField(default=1)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='authentication.student')),
            ],
            options={
                'ordering': ['-last_played'],
                'unique_together': {('student', 'game_id')},
            },
        ),
    ]
