services:
  - type: web
    name: little-learner-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: bash build.sh
    startCommand: gunicorn little_learner_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres:VarunBhoi%402711@db.uciwpoxpcurenwjzpbjc.supabase.co:5432/postgres
      - key: SUPABASE_URL
        value: https://uciwpoxpcurenwjzpbjc.supabase.co
      - key: SUPABASE_PUBLISHABLE_KEY
        value: sb_publishable_Hf78gLDO9kXgVpr6RX02xg_oQsFnrmb
