export const ALPHABET_DATA = [
  {
    letter: 'A',
    lower: 'a',
    word: 'Apple',
    wordMr: 'सफरचंद',
    phonics: 'says /æ/',
    phonicsMr: 'चा आवाज /æ/',
    soundExample: 'A says /æ/ as in Apple!',
    soundExampleMr: 'A सफरचंद (Apple)!',
    color: '#ef4444',
    bg: '#fee2e2',
    borderColor: '#fca5a5'
  },
  {
    letter: 'B',
    lower: 'b',
    word: 'Ball',
    wordMr: 'चेंडू',
    phonics: 'says /b/',
    phonicsMr: 'चा आवाज /b/',
    soundExample: 'B says /b/ as in Ball!',
    soundExampleMr: 'B चेंडू (Ball)!',
    color: '#3b82f6',
    bg: '#dbeafe',
    borderColor: '#93c5fd'
  },
  {
    letter: 'C',
    lower: 'c',
    word: 'Cat',
    wordMr: 'मांजर',
    phonics: 'says /k/',
    phonicsMr: 'चा आवाज /k/',
    soundExample: 'C says /k/ as in Cat!',
    soundExampleMr: 'C मांजर (Cat)!',
    color: '#f59e0b',
    bg: '#fef3c7',
    borderColor: '#fde68a'
  },
  {
    letter: 'D',
    lower: 'd',
    word: 'Dog',
    wordMr: 'कुत्रा',
    phonics: 'says /d/',
    phonicsMr: 'चा आवाज /d/',
    soundExample: 'D says /d/ as in Dog!',
    soundExampleMr: 'D कुत्रा (Dog)!',
    color: '#10b981',
    bg: '#d1fae5',
    borderColor: '#6ee7b7'
  },
  {
    letter: 'E',
    lower: 'e',
    word: 'Elephant',
    wordMr: 'हत्ती',
    phonics: 'says /e/',
    phonicsMr: 'चा आवाज /e/',
    soundExample: 'E says /e/ as in Elephant!',
    soundExampleMr: 'E हत्ती (Elephant)!',
    color: '#8b5cf6',
    bg: '#ede9fe',
    borderColor: '#c4b5fd'
  },
  {
    letter: 'F',
    lower: 'f',
    word: 'Frog',
    wordMr: 'बेडूक',
    phonics: 'says /f/',
    phonicsMr: 'चा आवाज /f/',
    soundExample: 'F says /f/ as in Frog!',
    soundExampleMr: 'F बेडूक (Frog)!',
    color: '#16a34a',
    bg: '#dcfce7',
    borderColor: '#86efac'
  },
  {
    letter: 'G',
    lower: 'g',
    word: 'Grapes',
    wordMr: 'द्राक्षे',
    phonics: 'says /g/',
    phonicsMr: 'चा आवाज /g/',
    soundExample: 'G says /g/ as in Grapes!',
    soundExampleMr: 'G द्राक्षे (Grapes)!',
    color: '#9333ea',
    bg: '#f3e8ff',
    borderColor: '#d8b4fe'
  },
  {
    letter: 'H',
    lower: 'h',
    word: 'Hat',
    wordMr: 'टोपी',
    phonics: 'says /h/',
    phonicsMr: 'चा आवाज /h/',
    soundExample: 'H says /h/ as in Hat!',
    soundExampleMr: 'H टोपी (Hat)!',
    color: '#ec4899',
    bg: '#fce7f3',
    borderColor: '#f9a8d4'
  },
  {
    letter: 'I',
    lower: 'i',
    word: 'Ice Cream',
    wordMr: 'आईस्क्रीम',
    phonics: 'says /aɪ/',
    phonicsMr: 'चा आवाज /aɪ/',
    soundExample: 'I says /aɪ/ as in Ice Cream!',
    soundExampleMr: 'I आईस्क्रीम (Ice Cream)!',
    color: '#06b6d4',
    bg: '#cffafe',
    borderColor: '#67e8f9'
  },
  {
    letter: 'J',
    lower: 'j',
    word: 'Juice',
    wordMr: 'रस (ज्यूस)',
    phonics: 'says /dʒ/',
    phonicsMr: 'चा आवाज /dʒ/',
    soundExample: 'J says /dʒ/ as in Juice!',
    soundExampleMr: 'J रस (Juice)!',
    color: '#f97316',
    bg: '#ffedd5',
    borderColor: '#fdba74'
  },
  {
    letter: 'K',
    lower: 'k',
    word: 'Kite',
    wordMr: 'पतंग',
    phonics: 'says /k/',
    phonicsMr: 'चा आवाज /k/',
    soundExample: 'K says /k/ as in Kite!',
    soundExampleMr: 'K पतंग (Kite)!',
    color: '#0284c7',
    bg: '#e0f2fe',
    borderColor: '#7dd3fc'
  },
  {
    letter: 'L',
    lower: 'l',
    word: 'Lion',
    wordMr: 'सिंह',
    phonics: 'says /l/',
    phonicsMr: 'चा आवाज /l/',
    soundExample: 'L says /l/ as in Lion!',
    soundExampleMr: 'L सिंह (Lion)!',
    color: '#eab308',
    bg: '#fef9c3',
    borderColor: '#fde047'
  },
  {
    letter: 'M',
    lower: 'm',
    word: 'Monkey',
    wordMr: 'माकड',
    phonics: 'says /m/',
    phonicsMr: 'चा आवाज /m/',
    soundExample: 'M says /m/ as in Monkey!',
    soundExampleMr: 'M माकड (Monkey)!',
    color: '#b45309',
    bg: '#fef3c7',
    borderColor: '#fde68a'
  },
  {
    letter: 'N',
    lower: 'n',
    word: 'Nest',
    wordMr: 'घरटे',
    phonics: 'says /n/',
    phonicsMr: 'चा आवाज /n/',
    soundExample: 'N says /n/ as in Nest!',
    soundExampleMr: 'N घरटे (Nest)!',
    color: '#78716c',
    bg: '#f5f5f4',
    borderColor: '#d6d3d1'
  },
  {
    letter: 'O',
    lower: 'o',
    word: 'Owl',
    wordMr: 'घुबड',
    phonics: 'says /ɒ/',
    phonicsMr: 'चा आवाज /ɒ/',
    soundExample: 'O says /ɒ/ as in Owl!',
    soundExampleMr: 'O घुबड (Owl)!',
    color: '#6366f1',
    bg: '#e0e7ff',
    borderColor: '#a5b4fc'
  },
  {
    letter: 'P',
    lower: 'p',
    word: 'Panda',
    wordMr: 'पांडा',
    phonics: 'says /p/',
    phonicsMr: 'चा आवाज /p/',
    soundExample: 'P says /p/ as in Panda!',
    soundExampleMr: 'P पांडा (Panda)!',
    color: '#0f172a',
    bg: '#f1f5f9',
    borderColor: '#cbd5e1'
  },
  {
    letter: 'Q',
    lower: 'q',
    word: 'Queen',
    wordMr: 'राणी',
    phonics: 'says /kw/',
    phonicsMr: 'चा आवाज /kw/',
    soundExample: 'Q says /kw/ as in Queen!',
    soundExampleMr: 'Q राणी (Queen)!',
    color: '#a855f7',
    bg: '#f3e8ff',
    borderColor: '#d8b4fe'
  },
  {
    letter: 'R',
    lower: 'r',
    word: 'Rainbow',
    wordMr: 'इंद्रधनुष्य',
    phonics: 'says /r/',
    phonicsMr: 'चा आवाज /r/',
    soundExample: 'R says /r/ as in Rainbow!',
    soundExampleMr: 'R इंद्रधनुष्य (Rainbow)!',
    color: '#f43f5e',
    bg: '#ffe4e6',
    borderColor: '#fda4af'
  },
  {
    letter: 'S',
    lower: 's',
    word: 'Star',
    wordMr: 'चांदणी',
    phonics: 'says /s/',
    phonicsMr: 'चा आवाज /s/',
    soundExample: 'S says /s/ as in Star!',
    soundExampleMr: 'S चांदणी (Star)!',
    color: '#f59e0b',
    bg: '#fef3c7',
    borderColor: '#fde68a'
  },
  {
    letter: 'T',
    lower: 't',
    word: 'Tiger',
    wordMr: 'वाघ',
    phonics: 'says /t/',
    phonicsMr: 'चा आवाज /t/',
    soundExample: 'T says /t/ as in Tiger!',
    soundExampleMr: 'T वाघ (Tiger)!',
    color: '#ea580c',
    bg: '#ffedd5',
    borderColor: '#fdba74'
  },
  {
    letter: 'U',
    lower: 'u',
    word: 'Umbrella',
    wordMr: 'छत्री',
    phonics: 'says /ʌ/',
    phonicsMr: 'चा आवाज /ʌ/',
    soundExample: 'U says /ʌ/ as in Umbrella!',
    soundExampleMr: 'U छत्री (Umbrella)!',
    color: '#0284c7',
    bg: '#e0f2fe',
    borderColor: '#7dd3fc'
  },
  {
    letter: 'V',
    lower: 'v',
    word: 'Violin',
    wordMr: 'व्हायोलिन',
    phonics: 'says /v/',
    phonicsMr: 'चा आवाज /v/',
    soundExample: 'V says /v/ as in Violin!',
    soundExampleMr: 'V व्हायोलिन (Violin)!',
    color: '#7c3aed',
    bg: '#ede9fe',
    borderColor: '#c4b5fd'
  },
  {
    letter: 'W',
    lower: 'w',
    word: 'Watermelon',
    wordMr: 'कलिंगड',
    phonics: 'says /w/',
    phonicsMr: 'चा आवाज /w/',
    soundExample: 'W says /w/ as in Watermelon!',
    soundExampleMr: 'W कलिंगड (Watermelon)!',
    color: '#10b981',
    bg: '#d1fae5',
    borderColor: '#6ee7b7'
  },
  {
    letter: 'X',
    lower: 'x',
    word: 'Xylophone',
    wordMr: 'झायलोफोन',
    phonics: 'says /ks/',
    phonicsMr: 'चा आवाज /ks/',
    soundExample: 'X says /ks/ as in Xylophone!',
    soundExampleMr: 'X झायलोफोन (Xylophone)!',
    color: '#06b6d4',
    bg: '#cffafe',
    borderColor: '#67e8f9'
  },
  {
    letter: 'Y',
    lower: 'y',
    word: 'Yo-yo',
    wordMr: 'यो-यो',
    phonics: 'says /j/',
    phonicsMr: 'चा आवाज /j/',
    soundExample: 'Y says /j/ as in Yo-yo!',
    soundExampleMr: 'Y यो-यो (Yo-yo)!',
    color: '#f59e0b',
    bg: '#fef3c7',
    borderColor: '#fde68a'
  },
  {
    letter: 'Z',
    lower: 'z',
    word: 'Zebra',
    wordMr: 'झेब्रा',
    phonics: 'says /z/',
    phonicsMr: 'चा आवाज /z/',
    soundExample: 'Z says /z/ as in Zebra!',
    soundExampleMr: 'Z झेब्रा (Zebra)!',
    color: '#334155',
    bg: '#f1f5f9',
    borderColor: '#cbd5e1'
  }
];
