export const ALPHABET_DATA = [
  {
    letter: 'A',
    lower: 'a',
    word: 'Apple',
    emoji: '🍎',
    phonics: 'says /æ/',
    soundExample: 'A says /æ/ as in Apple!',
    color: '#ef4444',
    bg: '#fee2e2',
    borderColor: '#fca5a5'
  },
  {
    letter: 'B',
    lower: 'b',
    word: 'Ball',
    emoji: '⚽',
    phonics: 'says /b/',
    soundExample: 'B says /b/ as in Ball!',
    color: '#3b82f6',
    bg: '#dbeafe',
    borderColor: '#93c5fd'
  },
  {
    letter: 'C',
    lower: 'c',
    word: 'Cat',
    emoji: '🐱',
    phonics: 'says /k/',
    soundExample: 'C says /k/ as in Cat!',
    color: '#f59e0b',
    bg: '#fef3c7',
    borderColor: '#fde68a'
  },
  {
    letter: 'D',
    lower: 'd',
    word: 'Dog',
    emoji: '🐶',
    phonics: 'says /d/',
    soundExample: 'D says /d/ as in Dog!',
    color: '#10b981',
    bg: '#d1fae5',
    borderColor: '#6ee7b7'
  },
  {
    letter: 'E',
    lower: 'e',
    word: 'Elephant',
    emoji: '🐘',
    phonics: 'says /e/',
    soundExample: 'E says /e/ as in Elephant!',
    color: '#8b5cf6',
    bg: '#ede9fe',
    borderColor: '#c4b5fd'
  },
  {
    letter: 'F',
    lower: 'f',
    word: 'Frog',
    emoji: '🐸',
    phonics: 'says /f/',
    soundExample: 'F says /f/ as in Frog!',
    color: '#16a34a',
    bg: '#dcfce7',
    borderColor: '#86efac'
  },
  {
    letter: 'G',
    lower: 'g',
    word: 'Grapes',
    emoji: '🍇',
    phonics: 'says /g/',
    soundExample: 'G says /g/ as in Grapes!',
    color: '#9333ea',
    bg: '#f3e8ff',
    borderColor: '#d8b4fe'
  },
  {
    letter: 'H',
    lower: 'h',
    word: 'Hat',
    emoji: '👒',
    phonics: 'says /h/',
    soundExample: 'H says /h/ as in Hat!',
    color: '#ec4899',
    bg: '#fce7f3',
    borderColor: '#f9a8d4'
  },
  {
    letter: 'I',
    lower: 'i',
    word: 'Ice Cream',
    emoji: '🍦',
    phonics: 'says /aɪ/',
    soundExample: 'I says /aɪ/ as in Ice Cream!',
    color: '#06b6d4',
    bg: '#cffafe',
    borderColor: '#67e8f9'
  },
  {
    letter: 'J',
    lower: 'j',
    word: 'Juice',
    emoji: '🧃',
    phonics: 'says /dʒ/',
    soundExample: 'J says /dʒ/ as in Juice!',
    color: '#f97316',
    bg: '#ffedd5',
    borderColor: '#fdba74'
  },
  {
    letter: 'K',
    lower: 'k',
    word: 'Kite',
    emoji: '🪁',
    phonics: 'says /k/',
    soundExample: 'K says /k/ as in Kite!',
    color: '#0284c7',
    bg: '#e0f2fe',
    borderColor: '#7dd3fc'
  },
  {
    letter: 'L',
    lower: 'l',
    word: 'Lion',
    emoji: '🦁',
    phonics: 'says /l/',
    soundExample: 'L says /l/ as in Lion!',
    color: '#eab308',
    bg: '#fef9c3',
    borderColor: '#fde047'
  },
  {
    letter: 'M',
    lower: 'm',
    word: 'Monkey',
    emoji: '🐵',
    phonics: 'says /m/',
    soundExample: 'M says /m/ as in Monkey!',
    color: '#b45309',
    bg: '#fef3c7',
    borderColor: '#fde68a'
  },
  {
    letter: 'N',
    lower: 'n',
    word: 'Nest',
    emoji: '🪺',
    phonics: 'says /n/',
    soundExample: 'N says /n/ as in Nest!',
    color: '#78716c',
    bg: '#f5f5f4',
    borderColor: '#d6d3d1'
  },
  {
    letter: 'O',
    lower: 'o',
    word: 'Owl',
    emoji: '🦉',
    phonics: 'says /ɒ/',
    soundExample: 'O says /ɒ/ as in Owl!',
    color: '#6366f1',
    bg: '#e0e7ff',
    borderColor: '#a5b4fc'
  },
  {
    letter: 'P',
    lower: 'p',
    word: 'Panda',
    emoji: '🐼',
    phonics: 'says /p/',
    soundExample: 'P says /p/ as in Panda!',
    color: '#0f172a',
    bg: '#f1f5f9',
    borderColor: '#cbd5e1'
  },
  {
    letter: 'Q',
    lower: 'q',
    word: 'Queen',
    emoji: '👑',
    phonics: 'says /kw/',
    soundExample: 'Q says /kw/ as in Queen!',
    color: '#a855f7',
    bg: '#f3e8ff',
    borderColor: '#d8b4fe'
  },
  {
    letter: 'R',
    lower: 'r',
    word: 'Rainbow',
    emoji: '🌈',
    phonics: 'says /r/',
    soundExample: 'R says /r/ as in Rainbow!',
    color: '#f43f5e',
    bg: '#ffe4e6',
    borderColor: '#fda4af'
  },
  {
    letter: 'S',
    lower: 's',
    word: 'Star',
    emoji: '⭐',
    phonics: 'says /s/',
    soundExample: 'S says /s/ as in Star!',
    color: '#f59e0b',
    bg: '#fef3c7',
    borderColor: '#fde68a'
  },
  {
    letter: 'T',
    lower: 't',
    word: 'Tiger',
    emoji: '🐯',
    phonics: 'says /t/',
    soundExample: 'T says /t/ as in Tiger!',
    color: '#ea580c',
    bg: '#ffedd5',
    borderColor: '#fdba74'
  },
  {
    letter: 'U',
    lower: 'u',
    word: 'Umbrella',
    emoji: '☂️',
    phonics: 'says /ʌ/',
    soundExample: 'U says /ʌ/ as in Umbrella!',
    color: '#0284c7',
    bg: '#e0f2fe',
    borderColor: '#7dd3fc'
  },
  {
    letter: 'V',
    lower: 'v',
    word: 'Violin',
    emoji: '🎻',
    phonics: 'says /v/',
    soundExample: 'V says /v/ as in Violin!',
    color: '#7c3aed',
    bg: '#ede9fe',
    borderColor: '#c4b5fd'
  },
  {
    letter: 'W',
    lower: 'w',
    word: 'Watermelon',
    emoji: '🍉',
    phonics: 'says /w/',
    soundExample: 'W says /w/ as in Watermelon!',
    color: '#10b981',
    bg: '#d1fae5',
    borderColor: '#6ee7b7'
  },
  {
    letter: 'X',
    lower: 'x',
    word: 'Xylophone',
    emoji: '🎼',
    phonics: 'says /ks/',
    soundExample: 'X says /ks/ as in Xylophone!',
    color: '#06b6d4',
    bg: '#cffafe',
    borderColor: '#67e8f9'
  },
  {
    letter: 'Y',
    lower: 'y',
    word: 'Yo-yo',
    emoji: '🪀',
    phonics: 'says /j/',
    soundExample: 'Y says /j/ as in Yo-yo!',
    color: '#f59e0b',
    bg: '#fef3c7',
    borderColor: '#fde68a'
  },
  {
    letter: 'Z',
    lower: 'z',
    word: 'Zebra',
    emoji: '🦓',
    phonics: 'says /z/',
    soundExample: 'Z says /z/ as in Zebra!',
    color: '#334155',
    bg: '#f1f5f9',
    borderColor: '#cbd5e1'
  }
];
